#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared-functions

FACTER_VER="2.2.0"
PUPPET_VER="3.7.1"
PUPPETDB_VER="2.2.0"
PUPPETDB_TERMINUS_VER="2.2.0"

# Install Puppet Source
RELEASE=`uname -r`

if [[ $RELEASE =~ "el6" ]]; then
  PACKAGE="http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
elif [[ $RELEASE =~ "el7" ]]; then
  PACKAGE="http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm"
elif [[ $RELEASE =~ "fc19" ]]; then
  PACKAGE="http://yum.puppetlabs.com/puppetlabs-release-fedora-19.noarch.rpm"
elif [[ $RELEASE =~ "fc20" ]]; then
  PACKAGE="http://yum.puppetlabs.com/puppetlabs-release-fedora-20.noarch.rpm"
else
  echo "Unsupported distibution release..."
  exit 1
fi

if [ ! -f /etc/yum.repos.d/puppetlabs.repo ]; then
  rpm -ivh $PACKAGE
fi

# Install Puppet from APT sources
yum install -y \
  facter-$FACTER_VER \
  puppet-$PUPPET_VER \
  puppetdb-terminus-$PUPPETDB_TERMINUS_VER \

yum install -y unzip wget ruby git
gem install bundler deep_merge --no-ri --no-rdoc

touch /etc/vagrant-bootstrapped
