#!/usr/bin/env bash

bootstrap-st2workroom() {
    trace "'bootstrap-st2workroom' entering"

    log "Setting up st2workroom in environment $(environment)"
    if local-development-mode; then
        setup-current-working-directory-environment
    else
        setup-environment-from-git-branch
    fi

    install-puppetfile

}

bootstrap-puppet-st2() {
    trace "'bootstrap-puppet-st2' entering"

    local _repo="https://github.com/stackstorm/st2.git"
    local _module_dir="$(environment-dir)/modules/st2"
    local _module_backup_dir="$(random-tmpdir)"
    local _git_stage_dir="$(random-tmpdir)"

    git-safe-clone $_repo $_git_stage_dir "$(puppet-st2-version)"
    safe-copy $_module_dir $_module_backup_dir
    ensure-directory-absent $_module_dir
    safe-copy $_git_stage_dir $_module_dir
}

