name    'StackStorm-puppet'
version '0.1.0'
source ''
author 'Patrick Hoolboom'
license ''
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
