#!/usr/bin/env bash

variable-set() {
    if [[ -n "${1:?}" ]]; then true; else false; fi
}

string-equals() {
    if [[ "${1:?}" = "${2:?}" ]]; then true; else false; fi
}

execute-string() {
    eval "${1:?}"
}

pushd-quiet() {
    pushd "${1:?}" >> /dev/null 2>&1
}

current-directory() {
    echo "$(pwd)"
}

command-successfully-run() {
    eval "${1:?}"
    if [ $? -eq 0 ]; then true; else false; fi
}
