#!/usr/bin/env bash

variable-set() {
    local _var="${1:-}"
    if [[ -n "$_var" ]]; then
        true
    else
        false
    fi
}

string-equals() {
    local _a="${1:?}"
    local _b="${2:?}"
    if [[ "$_a" = "$_b" ]]; then true; else false; fi
}

execute-string() {
    local _command="${1:?}"
    eval $_command
}

pushd-quiet() {
    local _dir="${1:-+1}"
    pushd $_dir >> /dev/null 2>&1
}

current-directory() {
    local _dir=$(pwd)
}
