#!/usr/bin/env bash

install-apt-packages() {
    local _packages="${1:?}"

    update-apt-if-needed
    debug "Installing packages using apt-get: ${_packages}"
    DEBIAN_FRONTEND=noninteractive apt-get -y install $_packages
}

update-apt-if-needed() {
    DEBIAN_FRONTEND=noninteractive apt-get -y update
}
