#!/usr/bin/env bash

if file-exists /opt/rh/ruby193/enable; then

def init() {
    local _canary_file="/opt/rh/ruby193/enable"
    if file-exists $_canary_file; then
        debug "Sourcing ruby SCL from ${_canary_file}"
        source $_canary_file
    fi
}
