#!/usr/bin/env bash

git-ref-type() {
    local _git_ref="${1:?}"
    local _git_root_dir="${2:?}"

    trace "checking 'git-ref-type' for $_git_root_dir at ref $_git_ref"

    if git show-ref -q --verify "refs/heads/${_git_ref}" 2>/dev/null; then
        echo "branch"
    elif git show-ref -q --verify "refs/tags/${_git_ref}" 2>/dev/null; then
        echo "tag"
    elif git show-ref -q --verify "refs/remote/${_git_ref}" 2>/dev/null; then
        echo "remote"
    elif git rev-parse --verify "${_git_ref}^{commit}" >/dev/null 2>&1; then
        echo "hash"
    else
        echo "unknown"
    fi
    return 0
}

git-ref-is-branch() {
    local _dir="${1:?}"
    local _branch="${2:?}"
    local _ref_type=

    trace "checking 'git-ref-is-branch' for $_dir at ref $_branch"
    _ref_type="$(git-ref-type $_dir $_branch)"

    if string-equals $_ref_type "branch"; then true; else false; fi
}

git-ref-is-tag() {
    local _dir="${1:?}"
    local _branch="${2:?}"
    local _ref_type=

    _ref_type="$(git-ref-type $_dir $_branch)"
    trace "checking 'git-ref-is-tag' for $_dir at ref $_branch"

    if string-equals $_ref_type "tag"; then true; else false; fi
}

safe-git-clone() {
    local _repo="${1:?}"
    local _dest_dir="${2:?}"
    local _branch="${3:-master}"

    trace "'safe-clone-repo' for $_repo to $_dest_dir on branch $_branch"

    if directory-exists $_dest_dir; then
        safe-copy $_dest_dir random-tmpdir
        ensure-directory-absent $_dest_dir
    fi

    git clone $_repo $_dest_dir -b $_branch
}

destructive-git-clone() {
    local _repo="${1:?}"
    local _dest_dir="${2:?}"
    local _branch="${3:-master}"

    trace "'destructive-clone-repo' for $_repo to $_dest_dir on branch $_branch"
    ensure-directory-absent $_dest_dir
    safe-git-clone $_repo $_dest_dir $_branch
}

git-update-and-clean-hard() {
    local _dir="${1:?}"
    local _branch="${2:master}"

    trace "'git-update-and-clean-hard' for $_dir on branch $_branch"
    git-update-and-clean $_dir
    git-hard-reset $_dir $_branch
}

git-update-and-clean() {
    local _dir="${1:?}"
    pushd-quiet $_dir

    trace "'git-update-and-clean' for $_dir on branch $_branch"
    git fetch --all
    git gc --auto

    pushd-quiet
}

git-hard-reset() {
    local _dir="${1:?}"
    local _branch="${2:master}"

    pushd-quiet $_dir

    trace "'git-hard-reset' for ${_dir} on branch ${_branch}"
    git reset --hard $_branch

    pushd-quiet +1
}
