#!/usr/bin/env bash

#silence-info-messages() {
#    if variable-set $ST2_SILENCE_INFO; then true; else false; fi
#}

logger() {
    echo "[${1:?}] ${2:?}"
}

info() {
    if ! silence-info-messages; then
        logger "info" "${1:?}"
    fi
}

log() {
    logger "log" "${1:?}"
}

error() {
    logger "error" "${1:?}"
}

debug() {
    if debug-enabled; then
        logger "debug" "${1:?}"
    fi
}

trace () {
    if trace-enabled; then
        logger "trace" "${1:?}"
    fi
}

fail-loudly() {
    error "*******************************************************"
    error "${1:?}"
    error "*******************************************************"
    exit 1
}

log-file() {
    local _log_file=
    _log_file=/var/log/puppet.log

    if variable-set $LOG_FILE; then echo $LOG_FILE; else echo $_log_file; fi
}

send-all-output-to-log-file-and-stdout() {
    echo " 2>&1 | tee -a `log-file`"
}

send-all-output-to-log-file() {
    echo " >> `log-file` 2>&1"
}

trace-enabled() {
    if variable-set $TRACE; then true; else false; fi
}

debug-enabled() {
    if variable-set $DEBUG; then true; else false; fi
}
