#!/usr/bin/env bash

## OS Checks
is-root() {
    if [[ $(id -u) -eq 0 ]]; then true; else false; fi
}

node-name() {
    echo "$(hostname -s)"
}

os-is-linux() {
    if string-equals os-family "linux"; then true; else false; fi
}

dist-is-redhat() {
    if os-is-linux && file-exists "/etc/redhat-release"; then
        true
    else
        false
    fi
}

dist-is-debian() {
    if os-is-linux && file-exists "/etc/debian_version"; then
        true
    else
        false
    fi
}

os-revision() {
    if dist-is-redhat; then
        get-redhat-release
    else
        get-debian-release
    fi
}

get-redhat-release() {
    echo "$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)"
}

get-debian-release() {
    echo "$(cat /etc/debian_version)"
}

os-family() {
    echo "$(uname -s)" | to-lowercase
}

os-dist() {
    local _dist=

    if dist-is-redhat; then
        $_dist="redhat"
    elif dist-is-debian; then
        $_dist="debian"
    fi

    echo $_dist
}

os-major-version() {
    local _rev=
    if dist-is-redhat; then
        $_rev="$(os-revision) | cut -d '.' -f1"
        echo "$(execute-string $_rev)"
    else
        error "Unable to get os-major-version for $(os-dist)"
    fi
}

os-codename() {
    echo $(/usr/bin/lsb_release -c -s)
}

####
# Below this line are legacy imports. Do not rely on them,
# they will be going away soon

NODE=$(hostname -s)

# From http://www.novell.com/coolsolutions/feature/11251.html
OS=`uname -s`
REV=`uname -r`
MACH=`uname -m`

if [ "$OS" = "OpenBSD" ]; then
    ARCH=`arch -s`
    BUNDLE_PATH='bundle20'
elif [ "$OS" = "Linux" ]; then
	KERNEL=`uname -r`
  BUNDLE_PATH='bundle'
	if [ -f /etc/redhat-release ]; then
		DIST='RedHat'
		REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
    MAJORVER=`echo $REV | cut -d '.' -f1`
	elif [ -f /etc/SUSE-release ]; then
		DIST=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
		REV=`cat /etc/SUSE-release | tr "\n" ' ' | sed s/.*=\ //`
	elif [ -f /etc/debian_version ] ; then
		DIST="Debian"
		REV="`cat /etc/debian_version`"
    CODENAME=`/usr/bin/lsb_release -c -s`
	fi
fi
