#!/usr/bin/env bash

## OS Checks
is-root() {
    trace "'is-root': checking if user has root privileges"
    if [[ $(id -u) -eq 0 ]]; then true; else false; fi
}

node-name() {
    local _node=$(hostname -s)

    trace "getting 'node-name' for $_node"
    echo $_node
}

os-is-linux() {
    trace "'os-is-linux' checking to see if it's a linux box"

    if string-equals os-family "linux"; then true; else false; fi
}

dist-is-redhat() {
    trace "'dist-is-redhat' checking to see if it's a rhel box"

    if os-is-linux && file-exists "/etc/redhat-release"; then
        true
    else
        false
    fi
}

dist-is-debian() {
    trace "'dist-is-debian' checking to see if it's a rhel box"
    if os-is-linux && file-exists "/etc/debian_version"; then
        true
    else
        false
    fi
}

os-revision() {
    trace "'os-revision' checking OS revision"

    if dist-is-redhat; then
        get-redhat-release
    else
        get-debian-release
    fi
}

get-redhat-release() {
    trace "'get-redhat-release'"
    echo "$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)"
}

get-debian-release() {
    trace "'get-debian-release'"
    echo "$(cat /etc/debian_version)"
}

os-family() {
    local _os_family=$(uname -s)

    trace "'os-family' getting family name: $_os_family"
    to-lowercase "$(uname -s)"
}

os-dist() {
    local _dist=

    trace "'os-dist' checking..."

    if dist-is-redhat; then
        _dist="redhat"
    elif dist-is-debian; then
        _dist="debian"
    fi

    echo $_dist
}

os-major-version() {
    local _rev=

    trace "'os-major-version' attempting to detect..."

    if dist-is-redhat; then
        $_rev="$(os-revision) | cut -d '.' -f1"
        echo "$(execute-string $_rev)"
    else
        error "Unable to get os-major-version for $(os-dist)"
    fi
}

os-codename() {
    local _codename=$(/usr/bin/lsb_release -c -s)

    trace "'os-codename' grabbing codename: $_codename"
    echo $_codename
}

####
# Below this line are legacy imports. Do not rely on them,
# they will be going away soon

NODE=$(hostname -s)

# From http://www.novell.com/coolsolutions/feature/11251.html
OS=`uname -s`
REV=`uname -r`
MACH=`uname -m`

if [ "$OS" = "OpenBSD" ]; then
    ARCH=`arch -s`
    BUNDLE_PATH='bundle20'
elif [ "$OS" = "Linux" ]; then
	KERNEL=`uname -r`
  BUNDLE_PATH='bundle'
	if [ -f /etc/redhat-release ]; then
		DIST='RedHat'
		REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
    MAJORVER=`echo $REV | cut -d '.' -f1`
	elif [ -f /etc/SUSE-release ]; then
		DIST=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
		REV=`cat /etc/SUSE-release | tr "\n" ' ' | sed s/.*=\ //`
	elif [ -f /etc/debian_version ] ; then
		DIST="Debian"
		REV="`cat /etc/debian_version`"
    CODENAME=`/usr/bin/lsb_release -c -s`
	fi
fi
