#!/usr/bin/env bash

run-bootstrap-os() {
    eval "$(script-root)/bootstrap-os"
}

run-preflight-os() {
    eval "$(script-root)/preflight-os"
}

script-root() {
    echo "$(project-root)/script"
}

project-root() {
    if variable-set $PROJECT_ROOT; then
        echo $PROJECT_ROOT
    else
        echo "/opt/puppet"
    fi
}

installer-bootstrap-lock-file() {
    echo "/etc/st2workroom-bootstrapped"
}
