#!/usr/bin/env bash

yum-clean() {
    yum clean all
    yum clean dbcache
}

yum-update() {
    yum -y update
}

yum-install-packages() {
    yum -y install "${*:?}"
}

yum-installgroup() {
    local _group="$*"
    yum groupinstall -y "${*:?}"
}

rpm-install-package() {
    rpm -ivh "${1:?}"
}

install-epel() {
    local _epel_6="https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    local _epel_7="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

    if rhel-6; then
        install-rpm-package $_epel_6
    elif rhel-7; then
        install-rpm-package $_epel_7
    else
        error "enable to find EPEL package for $(os-family) $(os-major-version)"
    fi
}

install-scl() {
    yum-install-packages centos-release-SCL scl-utils
}

enable-cr() {
    yum-install-packages yum-utils
    yum-config-manager --enable cr
}

rhel-6() {
  if os-is-redhat && os-major-version "6"; then true; else false; fi
}

rhel-7() {
  if os-is-redhat && os-major-version "7"; then true; else false; fi
}
