#!/usr/bin/env bash

yum-clean() {
    yum clean all
    yum clean dbcache
}

yum-update() {
    yum -y update
}

yum-install-packages() {
    yum -y install "${*:?}"
}

yum-installgroup() {
    yum groupinstall -y "${*:?}"
}

rpm-install-package() {
    rpm -ivh "${1:?}"
}

install-epel() {
    local _epel_6=
    local _epel_7=
    _epel_6="https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    _epel_7="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

    if rhel-6; then
        install-rpm-package $_epel_6
    elif rhel-7; then
        install-rpm-package $_epel_7
    else
        error "enable to find EPEL package for $(os-family) $(os-major-version)"
    fi
}

install-scl() {
    yum-install-packages centos-release-SCL scl-utils
}

enable-cr() {
    yum-install-packages yum-utils
    yum-config-manager --enable cr
}

rhel-6() {
  if dist-is-redhat && os-major-version "6"; then true; else false; fi
}

rhel-7() {
  if dist-is-redhat && os-major-version "7"; then true; else false; fi
}

supported-redhat-distro() {
    if rhel-6; then true;
    elif rhel-7; then true;
    else false;
    fi
}

dist-is-redhat() {
    if os-is-linux && file-exists "/etc/redhat-release"; then true;
    else false;
    fi
}

get-redhat-release() {
    echo "$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)"
}
