#!/usr/bin/env bash

install-bundler-if-needed() {
    if ! executable-exists "bundler"; then
        install-gem bundler
    fi
}

install-ruby-if-needed() {
    if os-is-ubuntu; then
        install-rvm
    fi
}

install-gem() {
    local _gem="${1:?}"
    local _default_args="--no-ri --no-rdoc"
    local _log_dest=
    local _cmd=

    if debug-enabled; then
        $_log_dest="$(send-all-output-to-log-file-and-stdout)"
    else
        $_log_dest="$(send-all-output-to-log-file)"
    fi

    $_args="${_default_args} ${_log_dest}"
    $_cmd="gem install ${_gem} ${_args}"
    execute-string $_cmd
}

install-bundled-gems() {
    local _log_dest=
    local _default_args="--deployment --binstubs"
    local _args=
    local _cmd=

    pushd-quiet $(project-root)

    if debug-enabled; then
        _log_dest="$(send-all-output-to-log-file-and-stdout)"
    else
        _log_dest="$(send-all-output-to-log-file)"
    fi

    _args="${_default_args} ${_log_dest}"
    _cmd="$(bundler-command) install --path vendor/bundle ${_args}"
    execute-string $_cmd

    pushd-quiet +1
}

bundler-command() {
    if string-equals os-family "linux"; then
        echo "bundler"
    else
        error "Unable to find bundler binary. Aborting"
        exit 1
    fi
}


init-enable-ruby-scl() {
    local _canary_file="/opt/rh/ruby193/enable"

    if file-exists $_canary_file; then
        source $_canary_file
    fi
}
