#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# adds a prefix to each element in an array
#
# returns string
#
# @ add-prefix-to-each <prefix> <array>
add-prefix-to-each() {
    local _args_array=
    local _arg_len=
    local _prefix=
    local _array=
    local _blob=
    _args_array=($@)
    _arg_len=${#_args_array[@]}
    _prefix="${1:?}"
    _array="${@:2:$_args_len}"

    for element in $_array; do
        _blob="${_blob} ${_prefix} ${element}"
    done

    echo $_blob
}

# Convert any input to lowercase string
#
# returns string
#
# @ to-lowercase <str>
to-lowercase() {
    echo "${1:?}" | tr '[:upper:]' '[:lower:]'
}
