#!/usr/bin/env bash

add-prefix-to-each() {
    local _args_array=($@)
    local _arg_len=${#_args_array[@]}
    local _prefix="${1:?}"
    local _array="${@:2:$_args_len}"
    local _blob=

    for element in $_array; do
        _blob="${_blob} ${_prefix} ${element}"
    done

    echo $_blob
}

to-lowercase() {
    echo "${1:?}" | tr '[:upper:]' '[:lower:]'
}
