#!/usr/bin/env sh

INSTALL_URL="https://docs.stackstorm.com/install/index.html"

echo "AIO installer has been deprecated in favor of the new package-based installation."
echo "For a package based installation, please follow the instructions at ${INSTALL_URL}"
exit 2
