#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared-functions

# Install Pre-req for git
if [ -f /usr/bin/apt-get ]; then
  apt-get install -y git
fi

if [ -f /usr/bin/yum ]; then
  yum install -y git-core
fi

## Check to see if bootstrap has been done already...
if [ ! -f /etc/st2workroom-bootstrapped ]; then
  ## Might be an ubuntu box
  if [ -f /etc/lsb-release ]; then
    $DIR/bootstrap-ubuntu
  fi

  ## Or maybe a RedHat Node
  if [ -f /etc/redhat-release ]; then
    $DIR/bootstrap-redhat
  fi
fi
