#!/usr/bin/env bash
# This stand-alone script should be able to be used to kickstart a new node

PROJECT_ROOT=/opt/puppet

# Install Pre-req for git
if [ -f /usr/bin/apt-get ]; then
  apt-get install -y git
fi

if [ -f /usr/bin/yum ]; then
  yum install -y git-core
fi

if [ ! -f ${PROJECT_ROOT}/.git ]; then
  # Backup the directory in the event that masterless setup goes south
  if [ -d ${PROJECT_ROOT} ]; then
    mv ${PROJECT_ROOT} ${PROJECT_ROOT}.old
  fi
  git clone https://github.com/StackStorm/st2workroom ${PROJECT_ROOT}
fi

# Create Facter sink
if [ ! -d /etc/facter/facts.d ]; then
  echo "Setting up facter.d..."
  mkdir -p /etc/facter/facts.d
  echo "role=st2express" > /etc/facter/facts.d/role.txt
fi

# Start up the st2express bootstrap
${PROJECT_ROOT}/script/bootstrap-linux

# Converge the system
${PROJECT_ROOT}/script/puppet-apply

IPADDRESS=$(facter ipaddress)

echo "          _   ___     ____  _  __ "
echo "         | | |__ \   / __ \| |/ / "
echo "      ___| |_   ) | | |  | | ' /  "
echo "     / __| __| / /  | |  | |  <   "
echo "     \__ \ |_ / /_  | |__| | . \  "
echo "     |___/\__|____|  \____/|_|\_\ "
echo ""
echo "  st2 is installed and ready to use."
echo
echo "First time starting this machine up?"
echo "Visit https://${IPADDRESS}/setup to configure StackStorm"
echo
echo "Otherwise, head to https://${IPADDRESS} to access the WebUI"
echo
