#!/usr/bin/env sh
DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

PACKAGES=""

if [ $MAJORVER = "6" ]; then
    EPEL="https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    PACKAGES="scl-utils ruby193 ruby193-ruby-devel glibc glibc-headers glibc-devel nscd nc git unzip curl python27 python27-pip python27-virtualenv python27-devel augeas"
    SCL="centos-release-SCL"
elif [ $MAJORVER = "7" ]; then
    EPEL="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    PACKAGES="ruby ruby-devel rubygem-bundler unzip curl git-core"
fi

# Install EPEL on RHEL boxen
if [ -n "$EPEL" ]; then
    if [ ! -f /etc/yum.repos.d/epel.repo ]; then
        rpm -ivh $EPEL
    fi
fi

# If we're using the Software Collection Library, downlad the repo
# and get it ready for usage
if [ -n "$SCL" ]; then
    yum install -y $SCL
fi


yum clean all
yum clean dbcache
yum groupinstall -y "Development Tools"

if [ -n "$BUILD_RUBY" ]; then
  install_rvm
fi

yum install -y $PACKAGES
