#!/usr/bin/env bash
set -e
set -u
set -o pipefail

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

# start the operating system bootstrap. Ensures that any generic OS
# tasks are taken care of, and detect/load any OS family scripts to also
# process as part of bootstrap phase
#
# @ init-bootstrap-os
init-bootstrap-os() {
    local _os_family_preflight_script=
    local _lock_file=
    _os_family_preflight_script="$(project-root)/script/bootstrap-os-$(os-family)"
    _lock_file=$(installer-bootstrap-lock-file)

    if ! is-root; then
        show-help
        fail-loudly $(error-run-with-root-permissions)
    fi

    if file-exists $_os_family_preflight_script
        && file-does-not-exist $_lock_file;
    then
        execute-string $_os_family_preflight_script
        ensure-lock-file-exists $_lock_file
    elif file-exists $_os_family_preflight_script
        && force-mode;
    then execute-string $_os_family_preflight_script;
    elif file-exists $_lock_file;
    then
        verbose-loudly $(notice-lock-file-exists)
    else
        fail-loudly $(error-what-even-happened)
    fi
}

init-bootstrap-os
