#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared-functions

export DEBIAN_FRONTEND=noninteractive

# Make sure we have the bare minimum
if [ ! $(which curl) ]; then
  apt-get update
  apt-get install -y curl
fi

# Install Puppet Source
rm /etc/apt/sources.list.d/puppetlabs.list
curl -O http://apt.puppetlabs.com/puppetlabs-release-pc1-${DISTRIB_CODENAME}.deb
dpkg -i puppetlabs-release-pc1-${DISTRIB_CODENAME}.deb

apt-get update

apt-get -y install unzip wget ruby ruby-dev git
apt-get -y install puppet-agent ruby-bundler unzip wget ruby ruby-dev git
gem install bundler deep_merge --no-ri --no-rdoc

touch /etc/st2workroom-bootstrapped
