#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APT_UPDATE_FREQ=30
source $DIR/shared-functions

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -y install unzip wget ruby ruby-dev git curl
apt-get -y install ruby-bundler unzip wget ruby ruby-dev git
gem install bundler deep_merge --no-ri --no-rdoc

touch /etc/st2workroom-bootstrapped
