#!/usr/bin/env bash
DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

init-bootstrap-os-linux() {
    local _preflight_script="$(project-root)/script/bootstrap-$(os-family)-$(os-dist)"

    if ! is-root; then
        show-help
        fail-loudly "Please run with root permissions"
    fi

    if file-exists $_preflight_script; then
       execute-string $_preflight_script
    fi
}

# Kick off main entry
init-bootstrap-os-linux
