#!/usr/bin/env sh
set -e

if [ $(id -u) -ne 0 ]; then
    echo "Please run with root privileges"
    exit 1
fi

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

# Check to see if bootstrap has been done already...
# Bootstrap is responsible for retrieving core utilities:
#  * git
#  * wget
#  * ruby
#  * bundler
#
# Everything else beyond this is handled within the project
#
if [ ! -f /etc/st2workroom-bootstrapped ]; then
    if [ "$OS" = "Linux" ]; then
        if [ "$DIST" = "RedHat" ]; then
            $DIR/bootstrap-redhat
        elif [ "$DIST" = "Debian" ]; then
            $DIR/bootstrap-debian
        else
            echo "Unsupported OS."
            exit 1
        fi
    elif [ "$OS" = "OpenBSD" ]; then
        $DIR/bootstrap-openbsd
    fi
fi

touch /etc/st2workroom-bootstrapped
