#!/usr/bin/env sh
set -e

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

PACKAGES=""

if [ $MAJORVER = "6" ]; then
    EPEL="https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    RBEL="http://rbel.frameos.org/rbel6"
    PACKAGES="rubygems glibc glibc-headers glibc-devel nscd nc git unzip curl"
elif [ $MAJORVER = "7" ]; then
    EPEL="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    PACKAGES="ruby ruby-devel rubygem-bundler unzip curl git-core"
fi

# Install EPEL on RHEL boxen
if [ -n "$EPEL" ]; then
    rpm -ivh $EPEL
fi

if [ -n "$RBEL" ]; then
    rpm -ivh $RBEL
fi

yum clean all
yum clean dbcache
yum groupinstall -y "Development Tools"

if [ -n "$BUILD_RUBY" ]; then
  install_rvm
fi

yum install -y $PACKAGES
