#!/usr/bin/env bash

PROJECT_ROOT=/opt/puppet
export PATH=${PROJECT_ROOT}/bin:/usr/local/bin:$PATH
cd $PROJECT_ROOT

ST2_PATH=$(which st2)
ST2_IP=$(bundle exec facter st2_ip)
ST2_FQDN=$(bundle exec facter fqdn)
ST2_DATACENTER=$(bundle exec facter datacenter)

case $ST2_DATACENTER in
  vagrant)
    KICK_COMMAND="vagrant provision st2express"
    ;;
  *)
    KICK_COMMAND="update-system"
    ;;
esac

if [ -x "${ST2_PATH}" ]; then
  sudo st2 run core.local date &> /dev/null
  ACTIONEXIT=$?
  if [ ! "${ACTIONEXIT}" == 0 ]; then
    echo ""
    echo "OH NOES!"
    echo "Don't worry! Occasionally something goes wrong, and you just have"
    echo "to kick the tires a bit. Try re-provisioning the workroom with"
    echo ""
    echo "${KICK_COMMAND}"
    echo ""
    echo "If you don't happen to get the 'OK' after that, give us a shout!"
    echo "We don't want to leave you hanging! Come find your favorite way to"
    echo "contact us (slack, irc, groups, or just plain ol email) at"
    echo "http://stackstorm.com/contact"
    echo
    exit 2
  else
    echo ""
    echo ""
    echo ""
    echo "███████╗████████╗██████╗      ██████╗ ██╗  ██╗";
    echo "██╔════╝╚══██╔══╝╚════██╗    ██╔═══██╗██║ ██╔╝";
    echo "███████╗   ██║    █████╔╝    ██║   ██║█████╔╝ ";
    echo "╚════██║   ██║   ██╔═══╝     ██║   ██║██╔═██╗ ";
    echo "███████║   ██║   ███████╗    ╚██████╔╝██║  ██╗";
    echo "╚══════╝   ╚═╝   ╚══════╝     ╚═════╝ ╚═╝  ╚═╝";
    echo ""
    echo "  st2 is installed and ready to use."
    echo ""
    echo "First time starting this machine up?"
    echo "Visit https://${ST2_IP}/setup to configure StackStorm"
    echo ""
    echo "Otherwise, head to https://${ST2_FQDN} to access the WebUI"
  fi
fi
