#!/usr/bin/env bash
set -e
set -u
set -o pipefail

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

# Checks to ensure that the current version of the installer
# is compatable with the OS running.

compatable-os() {
    log "Passed OS Detection..."
}

incompatable-os() {
    local _error_message=
    _error_message=<<EOF
OH NO! Y U NO WORK?!

Well, bummer. It seems that you have found yourself at the end of a
long cavern. Ahead of you is darkness. You can hear the wind blowing
across your left ear

You are running on an unsupported OS. Good news there is a high chance
StackStorm can and *should* run on your OS. We're hard at work adding
adding additional support all the time

* Supported OS List: https://docs.stackstorm.com/install/all_in_one.html#supported-platforms

We could also use your help! Want to help us add OS support? Take a look at
https://stackstorm.reamaze.com/articles/adding-os-support-to-all-in-one-installer
and see if you can lend us a hand.

Don't forget to let us know if we can help out in any other way. Come find
us using your favorite communication mechanism, and we'll be there with a
hot cup of cocoa and some tips on how to get some automation happening!

$(st2-support-contact-information)
EOF

    fail-loud $_error_message
}

# Check to detect if the OS is a supported OS for StackStorm
init-check-os-compat() {
    if supported-redhat-distro
            || supported-debian-distro;
    then compatable-os;
    else incompatable-os;
    fi
}

init-check-os-compat
