#!/usr/bin/env sh

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

ST2_PATH=`which st2`

if [ -x "${ST2_PATH}" ]; then
  ST2_IP=`facter st2_ip`
  ST2_FQDN=`facter fqdn`
  ST2_DATACENTER=`facter datacenter`
  if [ "$ST2_DATACENTER" = "vagrant" ]; then
      KICK_COMMAND="vagrant provision st2enterprise"
  else
      KICK_COMMAND="update-system"
  fi

  sudo st2 run core.local date &> /dev/null
  ACTIONEXIT=$?
  if [ ! "${ACTIONEXIT}" = 0 ]; then
    echo ""
    echo "OH NOES!"
    echo "Don't worry! Occasionally something goes wrong, and you just have"
    echo "to kick the tires a bit. Try re-provisioning the workroom with"
    echo ""
    echo "${KICK_COMMAND}"
    echo ""
    echo "If you don't happen to get the 'OK' after that, give us a shout!"
    echo "We don't want to leave you hanging! Come find your favorite way to"
    echo "contact us (slack, irc, groups, or just plain ol email) at"
    echo "http://stackstorm.com/contact"
    echo
    exit 2
  else
    echo ""
    echo ""
    echo ""
    echo "███████╗████████╗██████╗      ██████╗ ██╗  ██╗";
    echo "██╔════╝╚══██╔══╝╚════██╗    ██╔═══██╗██║ ██╔╝";
    echo "███████╗   ██║    █████╔╝    ██║   ██║█████╔╝ ";
    echo "╚════██║   ██║   ██╔═══╝     ██║   ██║██╔═██╗ ";
    echo "███████║   ██║   ███████╗    ╚██████╔╝██║  ██╗";
    echo "╚══════╝   ╚═╝   ╚══════╝     ╚═════╝ ╚═╝  ╚═╝";
    echo ""
    echo "  st2 is installed and ready to use."
    echo ""
    echo "First time starting this machine up?"
    echo "Visit https://${ST2_IP}/setup to configure StackStorm"
    echo "Otherwise, head to https://${ST2_FQDN} to access the WebUI"
    echo ""
    echo "If you would like to use the CLI interface, please log out and"
    echo "login to your session again. This is necessary to properly source"
    echo "StackStorm ENV variables"
  fi
fi
