#!/usr/bin/env bash
set -e

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

# Checks to ensure that the current version of the installer
# is compatable with the OS running.

compatable_os() {
    echo "Passed OS Detection..."
    exit 0
}

incompatable_os() {
    echo ""
    echo "OH NO! Y U NO WORK?!"
    echo ""
    echo "Well, bummer. It seems that you have found yourself at the end of a"
    echo "long cavern. Ahead of you is darkness. You can hear the wind blowing"
    echo "across your left ear"
    echo ""
    echo "You are running on an unsupported OS. Good news there is a high chance"
    echo "StackStorm can and *should* run on your OS. We're hard at work adding"
    echo "adding additional support all the time"
    echo ""
    echo "* Supported OS List: https://docs.stackstorm.com/install/all_in_one.html#supported-platforms"
    echo ""
    echo "We could also use your help! Want to help us add OS support? Take a look at"
    echo "https://stackstorm.reamaze.com/articles/adding-os-support-to-all-in-one-installer"
    echo "and see if you can lend us a hand."
    echo ""
    echo "Don't forget to let us know if we can help out in any other way. Come find"
    echo "us using your favorite communication mechanism, and we'll be there with a"
    echo "hot cup of cocoa and some tips on how to get some automation happening!"
    echo ""
    echo "Email: support@stackstorm.com"
    echo "IRC: irc.freenode.net/#stackstorm"
    echo "Slack: https://stackstorm.com/community-signup"
    echo ""
    exit 1
}

if [ "$DIST" = "RedHat" ]; then
    case $MAJORVER in
    6|7)
        compatable_os
        ;;
    *)
        incompatable_os
        ;;
    esac
elif [ "$DIST" = "Debian" ]; then
    case $CODENAME in
    trusty)
        compatable_os
        ;;
    *)
        incompatable_os
        ;;
    esac
else
    not_compatable
fi

