#!/usr/bin/env bash
set -e

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

init-preflight-os() {
    eval _os_family_cmd=

    log "Ensure pre-flight libraries are setup..."
    install-bundled-gems project-root
    install-puppet-libraries project-root

    # Preflight Setup. Entry point to OS/Distro specific scripts
    if file-exists "${DIR}/preflight-os-$(os-family)"; then
        $_os_family_cmd="$DIR/preflight-os-$(os-family)"
        execute-string $_os_family_cmd
    fi
}

init-preflight-os
