#!/usr/bin/env sh
set -e

DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

APT_UPDATE_FREQ=30

## This is an operation that requires access to the internet. Let's make sure
## we're in an environment that will allow this.
##
## This value is set in Class['profile::infrastructure']
OFFLINE_MODE=`facter system_offline_mode`

update_apt() {
    echo "Updating Debian apt-cache..."
    apt-get update > /dev/null 2>&1
}

if [ "$OFFLINE_MODE" != "true" ]; then
  ## Only run if we haven't run APT in awhile. Speed up feedback loop
  if [ -f /var/lib/apt/periodic/update-success-stamp ]; then
      if [ `find /var/lib/apt/periodic/update-success-stamp -mmin +${APT_UPDATE_FREQ} | grep apt` ]; then
          update_apt
      fi
  else
    update_apt
  fi
fi
