#!/usr/bin/env bash
DIR=$( dirname "$(readlink -f "$0")" )
. $DIR/shared-functions

init-preflight-os-linux() {
    trace "'preflight-os-linux' entering"

    if file-exists "${DIR}/preflight-os-$(os-family)-$(os-dist)"; then
        debug "Running pre-flight for $(os-family)/$(os-dist)"
        $DIR/preflight-os-$(os-family)-$(os-dist)
    fi
}

init-preflight-os-linux
