#!/usr/bin/env bash
#
# To use, add to script
#
# DIR=$( dirname "$(readlink -f "$0")" )
# . $DIR/shared-functions
set -e
set -u
set -o pipefail

DIR=$( dirname "$(readlink -f "$0")" )

# Bash Helpers
source $DIR/lib/helpers/string-helpers
source $DIR/lib/helpers/file-helpers
source $DIR/lib/helpers/logging-helpers

# OS Helpers
source $DIR/lib/helpers/os-helpers
source $DIR/lib/helpers/debian-helpers
source $DIR/lib/helpers/redhat-helpers

# Tool Helpers
source $DIR/lib/helpers/rsync-helpers
source $DIR/lib/helpers/puppet-helpers
source $DIR/lib/helpers/git-helpers

# Language Helpers
source $DIR/lib/helpers/bash-helpers
source $DIR/lib/helpers/ruby-helpers

# Project Helpers
source $DIR/lib/helpers/project-helpers

# LEGACY! THESE ARE GOING AWAY
PROJECT_ROOT=/opt/puppet
PATH=${PROJECT_ROOT}/bin:/usr/local/bin:$PATH
