#!/usr/bin/env bash
#
# Required StackStorm AIO configuration functions

## THE ONLY GLOBAL VARIABLES
LOG_FILE="${AIO_LOGFILE:-/var/log/puppet.log}"
PROJECT_ROOT="${AIO_PROJECT_ROOT:-/opt/puppet}"

####################################


project-root() {
    echo $PROJECT_ROOT
}

default-log-file() {
    ensure-file-exists $LOG_FILE
    echo $LOG_FILE
}
